[package]
name = "pdfutil"
version = "0.1.0"
authors = ["Junfeng Liu <china.liujunfeng@gmail.com>"]
homepage = "https://github.com/J-F-Liu/lopdf"
documentation = "https://docs.rs/crate/lopdf/"
repository = "https://github.com/J-F-Liu/lopdf.git"
license = "MIT"
description = "A utility for PDF document manipulation."

[dependencies]
lopdf = {version = "0.8.0", path = "../"}
clap = "2.21.1"
