[package]
name = "lopdf"
version = "0.1.0"
authors = ["Junfeng Liu <china.liujunfeng@gmail.com>"]
repository = "https://github.com/J-F-Liu/lopdf.git"
homepage = "https://github.com/J-F-Liu/lopdf"
license = "MIT"
readme = "README.md"
description = "A Rust library for PDF document manipulation."

[dependencies]
