[package]
name = "lopdf"
version = "0.3.0"
authors = ["Junfeng Liu <china.liujunfeng@gmail.com>"]
homepage = "https://github.com/J-F-Liu/lopdf"
documentation = "https://docs.rs/lopdf/"
repository = "https://github.com/J-F-Liu/lopdf.git"
license = "MIT"
readme = "README.md"
description = "A Rust library for PDF document manipulation."

[dependencies]
pom = "0.6.0"
flate2 = "0.2.14"
linked-hash-map = "0.3.0"
